services:
  postgres:
    image: postgres:16-alpine
    container_name: eds_lab_postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eds_lab"]
      interval: 5s
      timeout: 3s
      retries: 10

  mailpit:
    image: axllent/mailpit:v1.21
    container_name: eds_lab_mailpit
    ports:
      - "1025:${SMTP_PORT}"
      - "8025:8025"

volumes:
  postgres_data:
